# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5467e27fd6962cbbdffa15f53b352544d7ede60e9c125919146a6aedbbcfb31059e8bad682ec0a84a1e9ef3037a157a499216452a55da0986ec422ea6fe73ba1

test:
  secret_key_base: e82cafb2962cb3c9a3309f3cb5bde8325d414e34a3fbba4229507d1a8fb678f8fa8c29be426a7edb412dcc20396ea5c2e7c1a244ae0c009eb11c137fdca3f27d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
